name: terragrunt-azure-deploy

env:
  tf_version: 1.6.2
  tg_version: 0.52.1

  # ✅ REQUIRED for Terraform OIDC auth
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  Plan:
    name: Plan
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Debug OIDC Token
        run: |
         echo "Event: $ {{ github.event_name }}"
         echo "Ref: ${{github.ref}}"
         

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Install Terraform
        run: |
          wget -q https://releases.hashicorp.com/terraform/${{ env.tf_version }}/terraform_${{ env.tf_version }}_linux_amd64.zip
          unzip terraform_${{ env.tf_version }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Install Terragrunt
        run: |
          sudo wget -q -O /usr/local/bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.tg_version }}/terragrunt_linux_amd64"
          sudo chmod +x /usr/local/bin/terragrunt
          terragrunt -v

      - name: Terragrunt Plan
        working-directory: terragrunt/azure/live
        env:
          TF_IN_AUTOMATION: true
        run: |
          terragrunt run-all plan --terragrunt-non-interactive


  Apply:
    name: Apply
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    needs: [Plan]

    environment:
      name: all-environments

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Install Terraform
        run: |
          wget -q https://releases.hashicorp.com/terraform/${{ env.tf_version }}/terraform_${{ env.tf_version }}_linux_amd64.zip
          unzip terraform_${{ env.tf_version }}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Install Terragrunt
        run: |
          sudo wget -q -O /usr/local/bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.tg_version }}/terragrunt_linux_amd64"
          sudo chmod +x /usr/local/bin/terragrunt
          terragrunt -v

      - name: Terragrunt Apply
        working-directory: terragrunt/azure/live
        env:
          TF_IN_AUTOMATION: true
        run: |
          terragrunt run-all apply --terragrunt-non-interactive --auto-approve


  #ignore      
















